name: Setup Branch Protection

on:
  workflow_dispatch:

permissions: write-all

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Configure branch protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: 'diegoizac',
              repo: 'christianitatis',
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['validate', 'audit', 'wait-for-approval']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
